using namespace std;
#include <iostream>
class Wielomian {
    int OkreslStopien(const char* napis);
    char* AnalizujJednomian(char* napis);
    void StworzWielomian();
    void WypelnijWielomian(char* napis);
    void PrzepiszWielomian(const float* tab, int st);
    void Dodawanie(const Wielomian& result, const Wielomian& w);
    void Odejmowanie(const Wielomian& result, const Wielomian& w);
    void Mnozenie(const Wielomian& result, const Wielomian& w);
public:
    float* wsp;
    int stopien;
    Wielomian();
    ~Wielomian();
    Wielomian(const char* napis);
    Wielomian(const float* tab, int st);
    Wielomian(int st, float ws);
    Wielomian(const Wielomian& w);
    Wielomian Pochodna();
    Wielomian operator+(const Wielomian& w);
    Wielomian operator+(double k);
    void operator+=(const Wielomian& w);
    void operator+=(double k);
    Wielomian operator-(const Wielomian& w);
    Wielomian operator-(double k);
    void operator-=(const Wielomian& w);
    void operator-=(double k);
    Wielomian operator*(const Wielomian& w);
    Wielomian operator*(double k);
    Wielomian operator/(const Wielomian& w);
    Wielomian operator/(double k);
    float operator()(double k);
    float operator[](int k);
    void operator/=(const Wielomian& w);
    void operator/=(double k);
    Wielomian operator%(const Wielomian& w);
    void operator%=(const Wielomian& w);
    void operator*=(const Wielomian& w);
    void operator*=(double k);
    bool operator==(const Wielomian& w);
    void operator=(const Wielomian& w);
    void Pokaz(ostream& o)const;
};
istream& operator>>(istream& o, Wielomian& w);
ostream& operator<<(ostream& o, const Wielomian& w);
Wielomian operator+(double k, const Wielomian& w);
Wielomian operator-(double k, const Wielomian& w);
Wielomian operator*(double k, const Wielomian& w);
char* UsunSpacje(const char* napis);
